version: '3.9'
name: tp1
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_LOGS=rabbit.log
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s
  result_handler:
    container_name: result_handler
    image: result_handler:latest
    entrypoint: python3 /main.py
    volumes:
      - ./result_handler:/result_handler:rw
    environment:
      - PYTHONUNBUFFERED=1
      - LISTEN_BACKLOG=5
      - TOTAL_CLIENTS=3
    depends_on:
      rabbitmq:
        condition: service_healthy
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONNECTED_NODES=3
    depends_on:
      rabbitmq:
        condition: service_healthy
  client_1:
    container_name: client_1
    image: client:latest
    entrypoint: python3 /main.py
    hostname: client_1
    volumes:
      - ./results:/results:rw
      - type: bind
        source: ./client/itineraries_random_demo_500K.csv
        target: /itineraries.csv
      - type: bind
        source: ./client/airports-codepublic.csv
        target: /airports-codepublic.csv
    environment:
      - PYTHONUNBUFFERED=1
      - ID=1
    depends_on:
      - server
  client_2:
    container_name: client_2
    image: client:latest
    entrypoint: python3 /main.py
    hostname: client_2
    volumes:
      - ./results:/results:rw
      - type: bind
        source: ./client/itineraries_random_demo_500K.csv
        target: /itineraries.csv
      - type: bind
        source: ./client/airports-codepublic.csv
        target: /airports-codepublic.csv
    environment:
      - PYTHONUNBUFFERED=1
      - ID=2
    depends_on:
      - server
  client_3:
    container_name: client_3
    image: client:latest
    entrypoint: python3 /main.py
    hostname: client_3
    volumes:
      - ./results:/results:rw
      - type: bind
        source: ./client/itineraries_random_demo_500K.csv
        target: /itineraries.csv
      - type: bind
        source: ./client/airports-codepublic.csv
        target: /airports-codepublic.csv
    environment:
      - PYTHONUNBUFFERED=1
      - ID=3
    depends_on:
      - server
  initial_column_cleaner_1:
    container_name: initial_column_cleaner_1
    image: column_cleaner:latest
    entrypoint: python3 /main.py
    hostname: initial_column_cleaner_1
    volumes: &id004
      - ./column_cleaner:/column_cleaner:rw
    environment: &id001
      - PYTHONUNBUFFERED=1
      - INPUT_QUEUE=full_flight_registers
      - OUTPUT_EXCHANGE=cleaned_flight_registers
      - REQUIRED_COLUMNS_FLIGHTS=op_code,client_id,legId,startingAirport,destinationAirport,travelDuration,baseFare,totalFare,totalTravelDistance,segmentsArrivalAirportCode,message_id
      - CONNECTED_NODES=3
    depends_on: &id002
      - group_by_id_1
      - group_by_id_2
      - group_by_id_3
      - query_2_column_filter_1
      - query_2_column_filter_2
      - query_2_column_filter_3
      - query_5_column_filter_1
      - query_5_column_filter_2
      - query_5_column_filter_3
      - group_by_id_avg_1
      - group_by_id_avg_2
      - group_by_id_avg_3

  filter_by_three_stopovers_1:
    container_name: filter_by_three_stopovers_1
    image: filter_by_three_stopovers:latest
    entrypoint: python3 /main.py
    hostname: filter_by_three_stopovers_1
    volumes: &id005
      - ./filter_by_three_stopovers:/filter_by_three_stopovers:rw
    environment: &id003
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=3
      - OUTPUT_QUEUE=output_1
      - OUTPUT_EXCHANGE=three_or_more_stopovers
      - COLUMNS_TO_FILTER=legId,client_id,startingAirport,destinationAirport,stopovers,totalFare,message_id
    depends_on: &id065
      - query_handler_1
      - query_handler_2
      - query_handler_3
      - group_by_route
  initial_column_cleaner_2:
    container_name: initial_column_cleaner_2
    image: column_cleaner:latest
    hostname: initial_column_cleaner_2
    entrypoint: python3 /main.py
    volumes: *id004
    environment: *id001
    depends_on: *id002
  initial_column_cleaner_3:
    container_name: initial_column_cleaner_3
    image: column_cleaner:latest
    hostname: initial_column_cleaner_3
    entrypoint: python3 /main.py
    volumes: *id004
    environment: *id001
    depends_on: *id002
  filter_by_three_stopovers_2:
    container_name: filter_by_three_stopovers_2
    image: filter_by_three_stopovers:latest
    hostname: filter_by_three_stopovers_2
    entrypoint: python3 /main.py
    volumes: *id005
    environment: *id003
    depends_on: *id065
  filter_by_three_stopovers_3:
    container_name: filter_by_three_stopovers_3
    image: filter_by_three_stopovers:latest
    hostname: filter_by_three_stopovers_3
    entrypoint: python3 /main.py
    volumes: *id005
    environment: *id003
    depends_on: *id065

  group_by_id_1:
    container_name: group_by_id_1
    image: group_by:latest
    entrypoint: python3 /main.py
    hostname: group_by_id_1
    volumes: &id008
      - ./group_by:/group_by:rw
    environment: &id006
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=3
      - FIELD_GROUP_BY=
      - INPUT_EXCHANGE=cleaned_flight_registers
      - LISTENING_QUEUE=filter_by_three_stopovers_groupby
      - QUEUE_GROUP_BY=filter_by_three_stopovers
      - INPUT_QUEUE=
      - HANDLE_FLIGHTS_LOG=false
    depends_on: &id007
      - filter_by_three_stopovers_1
      - filter_by_three_stopovers_2
      - filter_by_three_stopovers_3
  group_by_id_2:
    container_name: group_by_id_2
    image: group_by:latest
    hostname: group_by_id_2
    entrypoint: python3 /main.py
    volumes: *id008
    environment: *id006
    depends_on: *id007
  group_by_id_3:
    container_name: group_by_id_3
    image: group_by:latest
    hostname: group_by_id_3
    entrypoint: python3 /main.py
    volumes: *id008
    environment: *id006
    depends_on: *id007
  
  group_by_route:
    container_name: group_by_route
    image: group_by:latest
    entrypoint: python3 /main.py
    hostname: group_by_route
    volumes: *id008
    environment:
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=3
      - FIELD_GROUP_BY=startingAirport,destinationAirport
      - INPUT_EXCHANGE=three_or_more_stopovers
      - QUEUE_GROUP_BY=group_by_route_queue
      - LISTENING_QUEUE=group_by_route
      - INPUT_QUEUE=
      - SEVERAL_EOF=true
      - HANDLE_FLIGHTS_LOG=true
    depends_on:
      - reducer_group_by_route_1
      - reducer_group_by_route_2
      - reducer_group_by_route_3
  
  reducer_group_by_route_1:
    container_name: reducer_group_by_route_1
    image: reducer_group_by:latest
    hostname: reducer_group_by_route_1
    entrypoint: python3 /main.py
    volumes: &id009
      - ./reducer_group_by/3:/reducer_group_by:rw
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=route
      - INPUT_QUEUE=group_by_route_queue_1
      - OUTPUT_QUEUE=output_3
      - QUERY_NUMBER=3
      - QUERY_HANDLER_AMOUNT=1
    depends_on: &id051
      - query_handler_1
      - query_handler_2
      - query_handler_3
  reducer_group_by_route_2:
    container_name: reducer_group_by_route_2
    image: reducer_group_by:latest
    hostname: reducer_group_by_route_2
    entrypoint: python3 /main.py
    volumes: *id009
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=route
      - INPUT_QUEUE=group_by_route_queue_2
      - OUTPUT_QUEUE=output_3
      - QUERY_NUMBER=3
    depends_on: *id051
  reducer_group_by_route_3:
    container_name: reducer_group_by_route_3
    image: reducer_group_by:latest
    hostname: reducer_group_by_route_3
    entrypoint: python3 /main.py
    volumes: *id009
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=route
      - INPUT_QUEUE=group_by_route_queue_3
      - OUTPUT_QUEUE=output_3
      - QUERY_NUMBER=3
    depends_on: *id051
      
  query_2_column_filter_1:
    container_name: query_2_column_filter_1
    image: column_cleaner:latest
    entrypoint: python3 /main.py
    environment: &id015
      - PYTHONUNBUFFERED=1
      - INPUT_EXCHANGE=cleaned_flight_registers
      - INPUT_QUEUE=query_2_filter_queue
      - OUTPUT_QUEUE=distance_calculation
      - OUTPUT_EXCHANGE=airport_registers
      - REQUIRED_COLUMNS_FLIGHTS=op_code,message_id,client_id,legId,startingAirport,destinationAirport,totalTravelDistance,segmentsArrivalAirportCode
      - REQUIRED_COLUMNS_AIRPORTS=op_code,message_id,client_id,Airport Code,Latitude,Longitude
      - ROUTING_KEY=all
      - CONNECTED_NODES=3
    depends_on: &id016
      - distance_calculator_1
      - distance_calculator_2
      - distance_calculator_3
  query_2_column_filter_2:
    container_name: query_2_column_filter_2
    image: column_cleaner:latest
    entrypoint: python3 /main.py
    environment: *id015
    depends_on: *id016
  query_2_column_filter_3:
    container_name: query_2_column_filter_3
    image: column_cleaner:latest
    entrypoint: python3 /main.py
    environment: *id015
    depends_on: *id016
  distance_calculator_1:
    container_name: distance_calculator_1
    image: distance_calculator:latest
    entrypoint: python3 /main.py
    hostname: distance_calculator_1
    volumes: &id019
      - ./distance_calculator:/distance_calculator:rw
    environment: &id017
      - PYTHONUNBUFFERED=1
      - INPUT_QUEUE=distance_calculation
      - INPUT_EXCHANGE=airport_registers
      - OUTPUT_QUEUE=output_2
    depends_on: *id051
  distance_calculator_2:
    container_name: distance_calculator_2
    image: distance_calculator:latest
    hostname: distance_calculator_2
    entrypoint: python3 /main.py
    volumes: *id019
    environment: *id017
    depends_on: *id051
  distance_calculator_3:
    container_name: distance_calculator_3
    image: distance_calculator:latest
    hostname: distance_calculator_3
    entrypoint: python3 /main.py
    volumes: *id019
    environment: *id017
    depends_on: *id051

  query_5_column_filter_1:
    container_name: query_5_column_filter_1
    image: column_cleaner:latest
    entrypoint: python3 /main.py
    hostname: query_5_column_filter_1
    volumes: *id004
    environment: &id020
      - PYTHONUNBUFFERED=1
      - INPUT_EXCHANGE=cleaned_flight_registers
      - INPUT_QUEUE=query_5_filter_queue
      - OUTPUT_QUEUE=mode_calculation
      - REQUIRED_COLUMNS_FLIGHTS=op_code,client_id,startingAirport,baseFare,message_id
      - CONNECTED_NODES=3
      - ROUTING_KEY=flights
    depends_on:
      - group_by_airport
  query_5_column_filter_2:
    container_name: query_5_column_filter_2
    image: column_cleaner:latest
    entrypoint: python3 /main.py
    hostname: query_5_column_filter_2
    volumes: *id004
    environment: *id020
    depends_on:
      - group_by_airport
  query_5_column_filter_3:
    container_name: query_5_column_filter_3
    image: column_cleaner:latest
    entrypoint: python3 /main.py
    hostname: query_5_column_filter_3
    volumes: *id004
    environment: *id020
    depends_on:
      - group_by_airport

  group_by_airport:
    container_name: group_by_airport
    image: group_by:latest
    entrypoint: python3 /main.py
    hostname: group_by_airport
    volumes: *id008
    environment:
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=3
      - FIELD_GROUP_BY=startingAirport
      - INPUT_EXCHANGE=
      - LISTENING_QUEUE=
      - QUEUE_GROUP_BY=group_by_airport_queue
      - INPUT_QUEUE=mode_calculation
      - SEVERAL_EOF=true
      - QUERY_5_EOF=true
      - HANDLE_FLIGHTS_LOG=true
    depends_on:
      - reducer_group_by_airport_1
      - reducer_group_by_airport_2
      - reducer_group_by_airport_3

  reducer_group_by_airport_1:
    container_name: reducer_group_by_airport_1
    image: reducer_group_by:latest
    entrypoint: python3 /main.py
    hostname: reducer_group_by_airport_1
    volumes: &id010
      - ./reducer_group_by/5:/reducer_group_by:rw
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=startingAirport
      - INPUT_QUEUE=group_by_airport_queue_1
      - OUTPUT_QUEUE=output_5
      - QUERY_NUMBER=5
    depends_on: *id051

  reducer_group_by_airport_2:
    container_name: reducer_group_by_airport_2
    image: reducer_group_by:latest
    entrypoint: python3 /main.py
    hostname: reducer_group_by_airport_2
    volumes: *id010
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=startingAirport
      - INPUT_QUEUE=group_by_airport_queue_2
      - OUTPUT_QUEUE=output_5
      - QUERY_NUMBER=5
    depends_on: *id051

  reducer_group_by_airport_3:
    container_name: reducer_group_by_airport_3
    image: reducer_group_by:latest
    entrypoint: python3 /main.py
    hostname: reducer_group_by_airport_3
    volumes: *id010
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=startingAirport
      - INPUT_QUEUE=group_by_airport_queue_3
      - OUTPUT_QUEUE=output_5
      - QUERY_NUMBER=5
    depends_on: *id051

  avg_calculator_1:
    container_name: avg_calculator_1
    image: avg_calculator:latest
    entrypoint: python3 /main.py
    hostname: avg_calculator_1
    volumes: &id020
      - ./avg_calculator:/avg_calculator:rw
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_QUEUE=avg_queue
      - ID=1
      - OUTPUT_EXCHANGE=partial_avg_results
      - EXCHANGE_QUEUE=partial_results_queue
      - REDUCERS_AMOUNT=3
    depends_on: &id022
      - filter_by_average_1
      - filter_by_average_2
      - filter_by_average_3

  avg_calculator_2:
    container_name: avg_calculator_2
    image: avg_calculator:latest
    entrypoint: python3 /main.py
    hostname: avg_calculator_2
    volumes: *id020
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_QUEUE=avg_queue
      - ID=2
      - OUTPUT_EXCHANGE=partial_avg_results
      - EXCHANGE_QUEUE=partial_results_queue
      - REDUCERS_AMOUNT=3
    depends_on: *id022

  avg_calculator_3:
    container_name: avg_calculator_3
    image: avg_calculator:latest
    entrypoint: python3 /main.py
    hostname: avg_calculator_3
    volumes: *id020
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_QUEUE=avg_queue
      - ID=3
      - OUTPUT_EXCHANGE=partial_avg_results
      - EXCHANGE_QUEUE=partial_results_queue
      - REDUCERS_AMOUNT=3
    depends_on: *id022

  filter_by_average_1:
    container_name: filter_by_average_1
    image: filter_by_average:latest
    entrypoint: python3 /main.py
    hostname: filter_by_average_1
    volumes: &id030
      - ./filter_by_average:/filter_by_average:rw
    environment:
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=3
      - INPUT_QUEUE=filter_queue
      - OUTPUT_QUEUE=filtered_by_average
      - INPUT_EXCHANGE=partial_avg_results
      - EXCHANGE_QUEUE=partial_avg_final_calculator
      - ID=1
    depends_on: &id031
      - group_by_route_query_4

  filter_by_average_2:
    container_name: filter_by_average_2
    image: filter_by_average:latest
    entrypoint: python3 /main.py
    hostname: filter_by_average_2
    volumes: *id030
    environment:
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=3
      - INPUT_QUEUE=filter_queue
      - OUTPUT_QUEUE=filtered_by_average
      - INPUT_EXCHANGE=partial_avg_results
      - EXCHANGE_QUEUE=partial_avg_final_calculator
      - ID=2
    depends_on: *id031

  filter_by_average_3:
    container_name: filter_by_average_3
    image: filter_by_average:latest
    entrypoint: python3 /main.py
    hostname: filter_by_average_3
    volumes: *id030
    environment:
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=3
      - INPUT_QUEUE=filter_queue
      - OUTPUT_QUEUE=filtered_by_average
      - INPUT_EXCHANGE=partial_avg_results
      - EXCHANGE_QUEUE=partial_avg_final_calculator
      - ID=3
    depends_on: *id031

  group_by_id_avg_1:
    container_name: group_by_id_avg_1
    image: group_by:latest
    entrypoint: python3 /main.py
    hostname: group_by_id_avg_1
    volumes: *id008
    environment: &id041
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=3
      - FIELD_GROUP_BY=
      - INPUT_EXCHANGE=cleaned_flight_registers
      - LISTENING_QUEUE=avg_calculator_groupby
      - QUEUE_GROUP_BY=avg_queue
      - QUEUE_GROUP_BY_SECONDARY=filter_queue
      - INPUT_QUEUE=
      - HANDLE_FLIGHTS_LOG=false
    depends_on: &id040
      - avg_calculator_1
      - avg_calculator_2
      - avg_calculator_3
      - filter_by_average_1
      - filter_by_average_2
      - filter_by_average_3

  group_by_id_avg_2:
    container_name: group_by_id_avg_2
    image: group_by:latest
    entrypoint: python3 /main.py
    hostname: group_by_id_avg_2
    volumes: *id008
    environment: *id041
    depends_on: *id040

  group_by_id_avg_3:
    container_name: group_by_id_avg_3
    image: group_by:latest
    entrypoint: python3 /main.py
    hostname: group_by_id_avg_3
    volumes: *id008
    environment: *id041
    depends_on: *id040

  group_by_route_query_4:
     container_name: group_by_route_query_4
     image: group_by:latest
     entrypoint: python3 /main.py
     hostname: group_by_route_query_4
     volumes: *id008
     environment:
       - PYTHONUNBUFFERED=1
       - REDUCERS_AMOUNT=3
       - EOF_REQUIRED=1
       - FIELD_GROUP_BY=startingAirport,destinationAirport
       - LISTENING_QUEUE=
       - INPUT_EXCHANGE=
       - QUEUE_GROUP_BY=group_by_route_queue_q4
       - INPUT_QUEUE=filtered_by_average
       - SEVERAL_EOF=true
       - HANDLE_FLIGHTS_LOG=true
     depends_on:
       - reducer_group_by_route_q4_1
       - reducer_group_by_route_q4_2
       - reducer_group_by_route_q4_3

  reducer_group_by_route_q4_1:
     container_name: reducer_group_by_route_q4_1
     image: reducer_group_by:latest
     entrypoint: python3 /main.py
     hostname: reducer_group_by_route_q4_1
     volumes: &id050
       - ./reducer_group_by/4:/reducer_group_by:rw
     environment:
       - PYTHONUNBUFFERED=1
       - FIELD_GROUP_BY=route
       - INPUT_QUEUE=group_by_route_queue_q4_1
       - OUTPUT_QUEUE=output_4
       - QUERY_NUMBER=4
     depends_on: *id051


  reducer_group_by_route_q4_2:
     container_name: reducer_group_by_route_q4_2
     image: reducer_group_by:latest
     entrypoint: python3 /main.py
     hostname: reducer_group_by_route_q4_2
     volumes: *id050
     environment:
       - PYTHONUNBUFFERED=1
       - FIELD_GROUP_BY=route
       - INPUT_QUEUE=group_by_route_queue_q4_2
       - OUTPUT_QUEUE=output_4
       - QUERY_NUMBER=4
     depends_on: *id051


  reducer_group_by_route_q4_3:
     container_name: reducer_group_by_route_q4_3
     image: reducer_group_by:latest
     entrypoint: python3 /main.py
     hostname: reducer_group_by_route_q4_3
     volumes: *id050
     environment:
       - PYTHONUNBUFFERED=1
       - FIELD_GROUP_BY=route
       - INPUT_QUEUE=group_by_route_queue_q4_3
       - OUTPUT_QUEUE=output_4
       - QUERY_NUMBER=4
     depends_on: *id051

  query_handler_1:
    container_name: query_handler_1
    image: query_handler:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - TOTAL_REDUCERS=3
    depends_on:
      rabbitmq:
        condition: service_healthy

  query_handler_2:
    container_name: query_handler_2
    image: query_handler:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - TOTAL_REDUCERS=3
    depends_on:
      rabbitmq:
        condition: service_healthy

  query_handler_3:
    container_name: query_handler_3
    image: query_handler:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - TOTAL_REDUCERS=3
    depends_on:
      rabbitmq:
        condition: service_healthy