version: '3.9'
name: tp1
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_LOGS=rabbit.log
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s
  result_handler:
    container_name: result_handler
    image: result_handler:latest
    entrypoint: python3 /main.py
    volumes:
      - ./result_handler:/result_handler:rw
    environment:
      - PYTHONUNBUFFERED=1
      - LISTEN_BACKLOG=1
    depends_on:
      rabbitmq:
        condition: service_healthy
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONNECTED_NODES=3
    depends_on:
      rabbitmq:
        condition: service_healthy
  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    volumes:
      - ./results:/results:rw
      - type: bind
        source: ./client/itineraries_random_demo.csv
        target: /itineraries.csv
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - server
  initial_column_cleaner_1:
    container_name: initial_column_cleaner_1
    image: column_cleaner:latest
    entrypoint: python3 /main.py
    hostname: initial_column_cleaner_1
    volumes: &id004
      - ./column_cleaner:/column_cleaner:rw
    environment: &id001
      - PYTHONUNBUFFERED=1
      - INPUT_QUEUE=full_flight_registers
      - OUTPUT_EXCHANGE=cleaned_flight_registers
      - REQUIRED_COLUMNS_FLIGHTS=op_code,legId,startingAirport,destinationAirport,travelDuration,baseFare,totalFare,totalTravelDistance,segmentsArrivalAirportCode,message_id
      - CONNECTED_NODES=3
    depends_on: &id002
      - filter_by_three_stopovers_1
      - filter_by_three_stopovers_2
      - filter_by_three_stopovers_3
  filter_by_three_stopovers_1:
    container_name: filter_by_three_stopovers_1
    image: filter_by_three_stopovers:latest
    entrypoint: python3 /main.py
    hostname: filter_by_three_stopovers_1
    volumes: &id005
      - ./filter_by_three_stopovers:/filter_by_three_stopovers:rw
    environment: &id003
      - PYTHONUNBUFFERED=1
      - OUTPUT_QUEUE=output_1
      - INPUT_QUEUE=filter_three_stop_overs_queue
      - INPUT_EXCHANGE=cleaned_flight_registers
      - OUTPUT_EXCHANGE=three_or_more_stopovers
      - COLUMNS_TO_FILTER=legId,startingAirport,destinationAirport,stopovers,totalFare,message_id
    depends_on:
      - query_handler
  query_handler:
    container_name: query_handler
    image: query_handler:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - TOTAL_REDUCERS=2
    depends_on:
      rabbitmq:
        condition: service_healthy
  initial_column_cleaner_2:
    container_name: initial_column_cleaner_2
    image: column_cleaner:latest
    hostname: initial_column_cleaner_2
    entrypoint: python3 /main.py
    volumes: *id004
    environment: *id001
    depends_on: *id002
  initial_column_cleaner_3:
    container_name: initial_column_cleaner_3
    image: column_cleaner:latest
    hostname: initial_column_cleaner_3
    entrypoint: python3 /main.py
    volumes: *id004
    environment: *id001
    depends_on: *id002
  filter_by_three_stopovers_2:
    container_name: filter_by_three_stopovers_2
    image: filter_by_three_stopovers:latest
    hostname: filter_by_three_stopovers_2
    entrypoint: python3 /main.py
    volumes: *id005
    environment: *id003
    depends_on:
      - query_handler
  filter_by_three_stopovers_3:
    container_name: filter_by_three_stopovers_3
    image: filter_by_three_stopovers:latest
    hostname: filter_by_three_stopovers_3
    entrypoint: python3 /main.py
    volumes: *id005
    environment: *id003
    depends_on:
      - query_handler
