# OPCODES
EOF_FLIGHTS_FILE = 0
FLIGHT_REGISTER = 1
EOF_AIRPORTS_FILE = 2
AIRPORT_REGISTER = 3
AVG_READY = 7
SIGTERM = 9
SIGTERM_B = b'\x09'
BATCH_SIZE = 1000
SERVER_ACK = 8
EOF_RESULTS = 0
EOF_B = b'\x00'

# STATES
BEGIN_EOF = 0
EOF_SENT = 1
